### ISSUE TITLE
Could please update to 2021 version?

### ISSUE THREAD

**Issue by tonghuix** [kognise/far-aim#1]
...Or maybe all the way to 2022 version?

**Comment by kognise** [comment]
I'm working on a couple massive improvements which should be out soon -
including updating to the latest version and switching to Pandoc.

**Comment by kognise** [comment]
I just released [v0.1.0](https://github.com/kognise/far-aim/releases/tag/v0.1.0) with FAR/AIM 2021 and massive improvements in other areas. Let me know if that's what you were looking for :)
